spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_jud
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
jwt:
  secret: "reemplazar-por-secreto"
  expiration: 3600
correo:
  from: no-reply@example.com
  host: smtp.example.com
  port: 587
  username: user
  password: pass
